apiVersion: 1

datasources:
  - name: Lab DP Metrics API
    type: yesoreyeram-infinity-datasource
    uid: LabDPAPI
    orgId: 1
    access: proxy
    url: http://localhost:8001
    isDefault: true
    jsonData:
      auth_type: none
    editable: false
    version: 1
