from dataclasses import dataclass, field
from typing import List, Optional

@dataclass
class PatientRecord:
    patient_id: str           # UUID4 as String
    ahv_number: str           # normalised (numbers only)
    family_name: str
    given_name: str
    gender: str               # 'male' | 'female' | 'other' | 'unknown'
    birthdate: str            # 'YYYY-MM-DD'
    canton: str               # 2 letter canton code
    id: Optional[int] = field(default=None, init=False)  # Auto-generated by DB